name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 9, 11, 14 ]

    steps:
    - name: Checkout GitHub sources
      uses: actions/checkout@v2
    - name: Setup JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: ./mvnw -B -nsu verify
    - name: Notify via Slack
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,took
        custom_payload: |
          {
            username: 'GitHub Actions',
            icon_url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW} JDK ${{ matrix.java }}\nBuild <https://github.com/${{github.repository}}/runs/${{github.run_number}}|${{github.run_number}}> (${process.env.AS_COMMIT}) of ${process.env.AS_REPO} by ${{github.actor}} ${{job.status}} in ${process.env.AS_TOOK}`,
            }]
          }
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: ${{ env.SLACK_WEBHOOK_URL != null }}
